### ISSUE TITLE
Feature: LDAP support

### ISSUE THREAD

**Issue by subdiox** [weseek/crowi-plus#137]
社内でLDAP認証によってユーザーの管理をしている場合、crowi-plus側で新しくユーザー情報を登録するのは二度手間になってしまいます。
そのため、crowi-plus側でLDAPに対応していただくことはできませんでしょうか。

ご検討よろしくお願いいたします。

**Comment by yuki-takei** [comment]
うちも crowi x 3 立ち上げてるんで、LDAP 連携機能があってフィルタリング出来たら便利そうだなとは思ってました。が…実装大変そうだな～っていう…そうでもないのかな。

npm package は ldapjs 一択っぽい。
https://www.npmjs.com/package/ldapjs

ちょっと検討してみます。

**Comment by yuki-takei** [comment]
課題山積
---------

- [ ] ensure to be able to login with username, password pair also
    - [ ] attach unique constraint to `username` field
- [ ] check whether the `username` is reserved in LDAP when registring NON-LDAP user

仕様検討メモ
--------------

できれば Google Account でのログインみたいに別ログインフォームを作るんじゃなくて、同一フォームに LDAP サーバー設定で予め決めた ID を入力してログインできるようにしたい。

あとはログイン時の参照優先度かなあ…基本的にLDAPよりオリジナルのユーザーDBの方を優先する、の方がいい気がする。LDAPを優先して見に行くと下記のようなケースに対応する工数が増える。

1. 先に username 「user1」が作成された
1. LDAP の設定を行った(かつLDAP には「user1」がいる)
1. 「user1」でログイン
    1. LDAP が優先されるので、ログインは成功、新規ユーザーを作成しようとする
    1. 既存のオリジナルの方の「user1」と被る

**Comment by yuki-takei** [comment]
https://www.npmjs.com/package/ldap-client

の方が `findandbind` があって便利かもしれない

**Comment by yuki-takei** [comment]
目処が立ちました。

http://passportjs.org/
https://github.com/vesse/passport-ldapauth

の組み合わせ。

**Comment by yuki-takei** [comment]
> オリジナルを優先すれば、LDAP由来の新規ユーザー作成は、オリジナルのユーザーDBに「user1」がいないときに限られる。

これはそうでもないか…
オリジナルDBには
  username: user1, password: hogehoge
が存在、LDAPには
  username: user1, password: fugafuga
が存在しているときに、user1, fugafuga の組み合わせで認証すると、LDAP の方で成功して結局同じ事になる。

**Comment by yuki-takei** [comment]
Progress -- 2017.10.24
-----------------------

- use [passport-ldapauth](https://github.com/vesse/passport-ldapauth)

### TODO

- [x] Ensure to be able to login with passport-ldapauth
- [ ] Admin Page
    - [x] Change and save the configurations
    - [x] Reset passport strategy when save the configurations
    - [x] Validation for configurations
    - [ ] Add an option to specify the property name to assign to username
    - [ ] Test connection button
- [ ] Register when login at the first time
    - [x] Prioritize loginPassport.loginWithLocal
    - [x] Create User account when not exists
    - [ ] Create LDAP account information and associate to User account
    - [ ] Show TBD message if [the case](https://github.com/weseek/crowi-plus/issues/137#issuecomment-332288333) occured
- [ ] Add 「Associate LDAP account」 and 「Disassociate LDAP account」 button to `/me/password`

**Comment by yuki-takei** [comment]
2.3.0-RC2 で実験中

**Comment by sig9org** [comment]
@yuki-takei 
LDAP 上で（OU では無く）特定グループに所属するユーザのみ、認証対象にすることは可能でしょうか？ 以下のように、特定 OU のユーザを認証することは 2.3.0-RC3 でも可能かと思います。

```
ldap://ADDRESS/ou=Users,dc=example,dc=com
```

ですが、以下のように Groups OU 内部に『Crowi』というグループを作り、このグループに所属するユーザを認証させたいのですが、上手く動作しません。 設定自体は保存出来るのですが、`Test Saved Configuration` から『Crowi』グループに所属させているユーザを認証させても、認証に失敗してしまいます。

```
ldap://ADDRESS/cn=Crowi,ou=Groups,dc=example,dc=com
```

以下のようにフィルタを書いてみたのですが、同様に上手く認証出来ませんでした。

```
(&(uid={{username}})(memberOf={{cn=Crowi,ou=Groups,dc=example,dc=com}}))
```

**Comment by yuki-takei** [comment]
@sig9org 
```
(&(uid={{username}})(memberOf={{cn=Crowi,ou=Groups,dc=example,dc=com}}))
```
は、 `uid=yuki,ou=people,dc=example,dc=com` という DN のユーザーの `memberOf` プロパティに `cn=Crowi,ou=Groups,dc=example,dc=com` といったグループDNが列挙されている場合に有効なフィルタです。なので、グループ側にユーザーUIDを登録しているような場合(例えば `cn=Crowi,ou=Groups,dc=example,dc=com` というグループDN の `memberUid` プロパティにユーザーDNが列挙されているような場合)のフィルタとしては使えません。

こちらは、内部で利用している
https://github.com/vesse/node-ldapauth-fork
の `groupSearch*` オプションに値を渡してあげれば実現できるらしいことはわかっていて、なる早で対応予定です。別の Issue を立てて対応しますので、もう少々お待ちください。

**Comment by sig9org** [comment]
@yuki-takei 
なるほど、承知しました（理解不足でスミマセン、、、ですが、勉強になりました！）

`groupSearch*` オプションの件も承知しました。 別 Issue の方をチェックするようにしますね。 レス、ありがとうございました！

**Comment by yuki-takei** [comment]
v2.3.0 リリースしました
